GRAPHS = $(./%.jgr)
JGRAPH_LOCAL = ../../../jgraph/jgraph
JGRAPH_HYDRA = /home/jplank/bin/LINUX-X86_64/jgraph
JGRAPH=$(JGRAPH_HYDRA)

all:
	$(JGRAPH) note_quarter.jgr   > note_quarter.ps
	$(JGRAPH) note_half.jgr      > note_half.ps
	$(JGRAPH) note_whole.jgr     > note_whole.ps
	$(JGRAPH) note_eighth.jgr    > note_eighth.ps
	$(JGRAPH) rest_quarter.jgr   > rest_quarter.ps
	$(JGRAPH) rest_half.jgr      > rest_half.ps
	$(JGRAPH) rest_whole.jgr     > rest_whole.ps
	$(JGRAPH) rest_eighth.jgr    > rest_eighth.ps
	$(JGRAPH) flat.jgr           > flat.ps
	$(JGRAPH) sharp.jgr          > sharp.ps
	$(JGRAPH) clef_treble.jgr    > clef_treble.ps
